name: Build and deploy to AWS

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "src/**"

  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build .jar file
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t usuarios:latest .
          docker tag usuarios:latest ${{ secrets.ECR_REPO_URL_API_USUARIOS }}:latest

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL_API_USUARIOS }}:latest

      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy API Usuario to Private EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i key.pem \
          ec2-user@${{ secrets.EC2_API_GATEWAY_PUBLIC_IP }} \
          "ssh -o StrictHostKeyChecking=no \
          -i ~/DevOps.pem \
          ec2-user@${{ secrets.EC2_API_USUARIOS_PRIVATE_IP }} \
          'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 089485767547.dkr.ecr.us-east-1.amazonaws.com && \
          docker pull ${{ secrets.ECR_REPO_URL_API_USUARIOS }}:latest && \
          docker rm -f usuarios || true && \
          docker run -d \
          -p 8081:8081 \
          -e GATEWAY_API_URL=http://${{ secrets.GATEWAY_API_URL }} \
          -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.EC2_DB_PRIVATE_IP }}:3306/db_usuarios \
          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          --name usuarios \
          --restart unless-stopped \
          ${{ secrets.ECR_REPO_URL_API_USUARIOS }}:latest \
          && docker image prune -af'"
